### ISSUE TITLE
ConsumerGroupCommand.PartitionAssignmentState

### ISSUE THREAD

**Issue by sijifeng** [gnuhpc/Kafka-zk-restapi#1]
ConsumerGroupCommand.PartitionAssignmentState . 这个protected 是无法访问的  为什么可以用  并且可以正常运行

**Comment by gnuhpc** [comment]
For you reference, please use the test case below:

package org.gnuhpc.bigdata

```
	@Test
	public void testProtected(){
		TestProtected.testClass test = new TestProtected.testClass("abcd");
		log.info(test.name());
	}
```

The testProtected is a scala object like this:
```
package org.gnuhpc.bigdata

object TestProtected {

  protected case class testClass(name: String)
}
```

Run the test and the result will be returned like this: 
2017-09-27 09:19:45 INFO  KafkaRestSpringbootApplicationTests:65 - abcd

Anyway, rather than believing the book you read, you'd better get your hands dirty for this. Close this issue.
